// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsVPysqZJL8ICpMidCOul7ESKOwIjo0sc',
    appId: '1:780674981928:web:f1beea5ac818d0c0d3151d',
    messagingSenderId: '780674981928',
    projectId: 'aqua-mates-a3786',
    authDomain: 'aqua-mates-a3786.firebaseapp.com',
    storageBucket: 'aqua-mates-a3786.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsnH02gIj8fm-4p2ZKnGY_ScuH55rURWY',
    appId: '1:780674981928:android:38c92315af9b9508d3151d',
    messagingSenderId: '780674981928',
    projectId: 'aqua-mates-a3786',
    storageBucket: 'aqua-mates-a3786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tsnGK-bIEbYukgNgDNpDXVNn9riB0S8',
    appId: '1:780674981928:ios:64b770f43616a668d3151d',
    messagingSenderId: '780674981928',
    projectId: 'aqua-mates-a3786',
    storageBucket: 'aqua-mates-a3786.appspot.com',
    iosBundleId: 'com.example.aquaMates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tsnGK-bIEbYukgNgDNpDXVNn9riB0S8',
    appId: '1:780674981928:ios:64b770f43616a668d3151d',
    messagingSenderId: '780674981928',
    projectId: 'aqua-mates-a3786',
    storageBucket: 'aqua-mates-a3786.appspot.com',
    iosBundleId: 'com.example.aquaMates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsVPysqZJL8ICpMidCOul7ESKOwIjo0sc',
    appId: '1:780674981928:web:b581579860fa2a35d3151d',
    messagingSenderId: '780674981928',
    projectId: 'aqua-mates-a3786',
    authDomain: 'aqua-mates-a3786.firebaseapp.com',
    storageBucket: 'aqua-mates-a3786.appspot.com',
  );
}
